config/routes.rb
Rails.application.routes.draw do
  resources :lottery_infos
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lottery_info.rb
class LotteryInfo < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_many :lottery_infos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lottery_infos_controller.rb
class LotteryInfosController < ApplicationController
  before_action :set_lottery_info, only: [:show, :edit, :update, :destroy]

  # GET /lottery_infos
  # GET /lottery_infos.json
  def index
    @lottery_infos = LotteryInfo.all
  end

  # GET /lottery_infos/1
  # GET /lottery_infos/1.json
  def show
  end

  # GET /lottery_infos/new
  def new
    @lottery_info = LotteryInfo.new
  end

  # GET /lottery_infos/1/edit
  def edit
  end

  # POST /lottery_infos
  # POST /lottery_infos.json
  def create
    @lottery_info = LotteryInfo.new(lottery_info_params)

    respond_to do |format|
      if @lottery_info.save
        format.html { redirect_to @lottery_info, notice: 'Lottery info was successfully created.' }
        format.json { render :show, status: :created, location: @lottery_info }
      else
        format.html { render :new }
        format.json { render json: @lottery_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lottery_infos/1
  # PATCH/PUT /lottery_infos/1.json
  def update
    respond_to do |format|
      if @lottery_info.update(lottery_info_params)
        format.html { redirect_to @lottery_info, notice: 'Lottery info was successfully updated.' }
        format.json { render :show, status: :ok, location: @lottery_info }
      else
        format.html { render :edit }
        format.json { render json: @lottery_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lottery_infos/1
  # DELETE /lottery_infos/1.json
  def destroy
    @lottery_info.destroy
    respond_to do |format|
      format.html { redirect_to lottery_infos_url, notice: 'Lottery info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lottery_info
      @lottery_info = LotteryInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lottery_info_params
      params.require(:lottery_info).permit(:user_id, :store, :lottery_type, :lottery_date, :purchase_cost, :lottery_number)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lottery_infos_helper.rb
module LotteryInfosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Edmonds</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lottery_infos/_form.html.erb
<%= form_for(lottery_info) do |f| %>
  <% if lottery_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lottery_info.errors.count, "error") %> prohibited this lottery_info from being saved:</h2>

      <ul>
      <% lottery_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :store %>
    <%= f.text_field :store %>
  </div>

  <div class="field">
    <%= f.label :lottery_type %>
    <%= f.text_field :lottery_type %>
  </div>

  <div class="field">
    <%= f.label :lottery_date %>
    <%= f.date_select :lottery_date %>
  </div>

  <div class="field">
    <%= f.label :purchase_cost %>
    <%= f.number_field :purchase_cost %>
  </div>

  <div class="field">
    <%= f.label :lottery_number %>
    <%= f.text_field :lottery_number %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lottery_infos/edit.html.erb
<h1>Editing Lottery Info</h1>

<%= render 'form', lottery_info: @lottery_info %>

<%= link_to 'Show', @lottery_info %> |
<%= link_to 'Back', lottery_infos_path %>

app/views/lottery_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lottery Infos</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Store</th>
      <th>Lottery type</th>
      <th>Lottery date</th>
      <th>Purchase cost</th>
      <th>Lottery number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lottery_infos.each do |lottery_info| %>
      <tr>
        <td><%= lottery_info.user %></td>
        <td><%= lottery_info.store %></td>
        <td><%= lottery_info.lottery_type %></td>
        <td><%= lottery_info.lottery_date %></td>
        <td><%= lottery_info.purchase_cost %></td>
        <td><%= lottery_info.lottery_number %></td>
        <td><%= link_to 'Show', lottery_info %></td>
        <td><%= link_to 'Edit', edit_lottery_info_path(lottery_info) %></td>
        <td><%= link_to 'Destroy', lottery_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lottery Info', new_lottery_info_path %>

app/views/lottery_infos/new.html.erb
<h1>New Lottery Info</h1>

<%= render 'form', lottery_info: @lottery_info %>

<%= link_to 'Back', lottery_infos_path %>

app/views/lottery_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @lottery_info.user %>
</p>

<p>
  <strong>Store:</strong>
  <%= @lottery_info.store %>
</p>

<p>
  <strong>Lottery type:</strong>
  <%= @lottery_info.lottery_type %>
</p>

<p>
  <strong>Lottery date:</strong>
  <%= @lottery_info.lottery_date %>
</p>

<p>
  <strong>Purchase cost:</strong>
  <%= @lottery_info.purchase_cost %>
</p>

<p>
  <strong>Lottery number:</strong>
  <%= @lottery_info.lottery_number %>
</p>

<%= link_to 'Edit', edit_lottery_info_path(@lottery_info) %> |
<%= link_to 'Back', lottery_infos_path %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>


<% @user.lottery_infos.each do |lottery_info| %>
<div class="card">
	<div class="card-block">
		<h4 class="card-title"><%= lottery_info.store %></h4>
		<p class="card-text"><%= lottery_info.lottery_type %></p>
		<%= lottery_info.lottery_date %>
		<%= lottery_info.purchase_cost %>
		<%= lottery_info.lottery_number %>
		<%= lottery_info.success_chance %>
		<%= lottery_info.winning_amount %>
	</div>
</div>
<% end %>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>